const labels={pending_review:"待筛选",ready_to_apply:"待投递",applied:"已投递",interview:"面试中",offer:"Offer",rejected:"已结束"};
const stageOrder=Object.keys(labels); let state={jobs:[],tasks:[],counts:{}}; let selectedStage="";
const $=s=>document.querySelector(s); const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const titleAliases={"AI Product Manager":"AI产品经理","Product Manager":"产品经理","Software Product Manager":"软件产品经理","Consumer Insights Intern":"消费者洞察实习生","2027 Intern Program - User Research direction":"2027实习计划-用户研究方向"};
const cityAliases={"Shenzhen":"深圳","Guangzhou":"广州","Dongguan":"东莞","Shenzhen（多城市可选）":"深圳（多城市可选）","Guangzhou/Shenzhen/Dongguan":"广州/深圳/东莞","Nanning":"南宁","Guilin":"桂林","Liuzhou":"柳州","Foshan":"佛山","Zhuhai":"珠海","Zhongshan":"中山","Huizhou":"惠州","Shantou":"汕头"};
const roleLabels={"AI Product":"AI产品","Product":"产品","UXR / Insight":"用户研究/洞察","Management Trainee":"管培生","Psychology Teaching":"心理教师相关","Other":"其他"};
const displayTitle=t=>titleAliases[t]||t; const displayCity=c=>cityAliases[c]||c; const roleLabel=r=>roleLabels[r]||r;
async function request(url,options={}){const res=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||"操作失败");return data}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)}
function unique(field){return [...new Set(state.jobs.map(j=>j[field]).filter(v=>v&&v!=="unknown"))].sort((a,b)=>a.localeCompare(b,"zh-CN"))}
function fillOptions(selector,values,label){const node=$(selector),current=node.value;node.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option>${esc(v)}</option>`).join("");node.value=current}
function renderStats(){const cards=[["pending_review","待筛选"],["ready_to_apply","待投递"],["applied","已投递"],["interview","面试中"],["offer","Offer"],["rejected","已结束"],["P0","P0 优先"],["psych","心理学触发"]];$("#stats").innerHTML=cards.map(([key,label])=>`<div class="stat ${key.toLowerCase()}"><span>${label}</span><strong>${key==="psych"?state.jobs.filter(j=>j.psychology_trigger).length:(state.counts[key]||0)}</strong></div>`).join("")}
function normaliseRecruitmentType(type,job={}){const raw=[type,job.title,job.notes,job.source,job.responsibilities].filter(Boolean).join(" ").toLowerCase();if(/实习|intern(ship)?/.test(raw))return "实习";if(/秋招|校园招聘|校招|应届生招聘|应届毕业生|campus|graduate[_\s-]?program/.test(raw))return "秋招";if(/社招|社会招聘|社会人才|社会岗|social/.test(raw))return "社招";return "待核验"}
function filteredJobs(){const q=$("#search").value.trim().toLowerCase(),province=$("#province").value,role=$("#role-family").value,recruitmentType=$("#recruitment-type").value,priority=$("#priority").value,stage=$("#stage").value||selectedStage,psych=$("#psychology").checked;return state.jobs.filter(j=>(!q||[j.company,j.title,j.city].join(" ").toLowerCase().includes(q))&&(!province||j.province===province)&&(!role||j.role_family===role)&&(!recruitmentType||normaliseRecruitmentType(j.recruitment_type,j)===recruitmentType)&&(!priority||j.priority===priority)&&(!stage||j.workflow_status===stage)&&(!psych||j.psychology_trigger))}
function renderTabs(){const all=["",...stageOrder];$("#stage-tabs").innerHTML=all.map(s=>`<button class="stage-tab ${selectedStage===s?"active":""}" data-stage="${s}">${s?labels[s]:"全部"}<span> ${s?(state.counts[s]||0):state.jobs.length}</span></button>`).join("");document.querySelectorAll(".stage-tab").forEach(b=>b.onclick=()=>{selectedStage=b.dataset.stage;$("#stage").value="";renderTabs();renderJobs()})}
function badge(text,type=""){return `<span class="pill ${type}">${esc(text)}</span>`}
function recruitmentBadge(type){const classNames={"秋招":"recruitment autumn","实习":"recruitment intern","社招":"recruitment social","待核验":"recruitment unverified"};return badge(type,classNames[type]||"recruitment unverified")}
function renderJobs(){const jobs=filteredJobs();$("#job-total").textContent=`${jobs.length} 个`;$("#job-list").innerHTML=jobs.length?jobs.map(j=>`<article class="job-card ${esc(j.priority)}" data-key="${encodeURIComponent(j.key)}"><div><h3 class="job-name">${esc(displayTitle(j.title))}</h3><p class="company">${esc(j.company)} · ${esc(j.province==="Guangdong"?"广东":j.province==="Guangxi"?"广西":j.province)}${j.city!=="unknown"?` · ${esc(displayCity(j.city))}`:""}</p><div class="job-meta">${recruitmentBadge(normaliseRecruitmentType(j.recruitment_type,j))}${badge(roleLabel(j.role_family),"blue")}${j.psychology_trigger?badge("心理学触发","orange"):""}${j.deadline?badge(`截止 ${j.deadline}`,"green"):""}${j.rank_score!==null?badge(`${j.rank_score} 分`):""}</div></div><div class="job-actions"><select class="select-compact priority-select" data-key="${encodeURIComponent(j.key)}"><option ${j.priority==="P0"?"selected":""}>P0</option><option ${j.priority==="P1"?"selected":""}>P1</option><option ${j.priority==="P2"?"selected":""}>P2</option><option ${j.priority==="Skip"?"selected":""}>Skip</option></select><select class="select-compact stage-select" data-key="${encodeURIComponent(j.key)}">${stageOrder.map(s=>`<option value="${s}" ${j.workflow_status===s?"selected":""}>${labels[s]}</option>`).join("")}</select></div></article>`).join(""):`<div class="empty">没有符合当前筛选条件的岗位。</div>`;document.querySelectorAll(".job-card").forEach(card=>card.onclick=e=>{if(e.target.tagName!=="SELECT")openDrawer(decodeURIComponent(card.dataset.key))});document.querySelectorAll(".priority-select").forEach(s=>s.onchange=()=>saveJob(decodeURIComponent(s.dataset.key),{priority:s.value}));document.querySelectorAll(".stage-select").forEach(s=>s.onchange=()=>saveJob(decodeURIComponent(s.dataset.key),{workflow_status:s.value}));}
function due(task){return task.deadline||task.date||""} function taskColumn(title,tasks){return `<div class="task-column"><h3>${title} <span class="count">${tasks.length}</span></h3>${tasks.length?tasks.map(t=>`<div class="task-item"><div><strong>${esc(t.title)}</strong><span>${esc(t.company||"未关联岗位")}${due(t)?` · ${esc(due(t))}`:""}</span></div><button data-task="${esc(t.task_id)}">完成</button></div>`).join(""):`<p class="muted">暂无事项</p>`}</div>`}
function renderTasks(){const date=new Date().toISOString().slice(0,10), plus7=new Date(Date.now()+7*864e5).toISOString().slice(0,10),pending=state.tasks.filter(t=>t.status==="pending"),overdue=pending.filter(t=>due(t)&&due(t)<date),today=pending.filter(t=>due(t)===date),week=pending.filter(t=>due(t)>date&&due(t)<=plus7),undated=pending.filter(t=>!due(t));$("#task-grid").innerHTML=[taskColumn("已逾期",overdue),taskColumn("今天",today),taskColumn("未来 7 天",week),taskColumn("待安排",undated)].join("");document.querySelectorAll("[data-task]").forEach(b=>b.onclick=()=>completeTask(b.dataset.task))}
function openDrawer(key){const j=state.jobs.find(x=>x.key===key);if(!j)return;const list=x=>Array.isArray(x)&&x.length?`<ul>${x.map(v=>`<li>${esc(v)}</li>`).join("")}</ul>`:"<p>暂无</p>";$("#drawer-content").innerHTML=`<p class="eyebrow">${esc(j.priority)} · ${esc(labels[j.workflow_status])}</p><h2>${esc(displayTitle(j.title))}</h2><p class="company">${esc(j.company)}</p><div class="drawer-grid detail-section"><div><span>工作地点</span><strong>${esc(j.province==="Guangdong"?"广东":j.province==="Guangxi"?"广西":j.province)} ${esc(displayCity(j.city))}</strong></div><div><span>招聘类型</span><strong>${esc(normaliseRecruitmentType(j.recruitment_type,j))}</strong></div><div><span>岗位方向</span><strong>${esc(roleLabel(j.role_family))}</strong></div><div><span>截止日期</span><strong>${esc(j.deadline||"未知")}</strong></div></div>${j.url?`<div class="detail-section"><a href="${esc(j.url)}" target="_blank" rel="noopener">打开岗位原链接 ↗</a></div>`:""}<div class="detail-section"><h3>心理学专业触发</h3><p>${j.psychology_trigger?`命中（${esc(j.psychology_trigger_type)}）：${esc(j.psychology_evidence||"待补充 JD 原文")}`:"未命中"}</p></div><div class="detail-section"><h3>匹配优势</h3>${list(j.strengths)}</div><div class="detail-section"><h3>待核对 / 缺口</h3>${list([...(j.gaps||[]),...(j.evidence_gaps||[]),...(j.hard_constraints||[])])}</div><div class="detail-section"><h3>岗位备注</h3><textarea id="notes-edit">${esc(j.notes)}</textarea><button class="button" id="save-notes">保存备注</button></div>`;$("#drawer").classList.add("open");$("#drawer").setAttribute("aria-hidden","false");$("#save-notes").onclick=()=>saveJob(key,{notes:$("#notes-edit").value})}
async function saveJob(key,body){try{await request(`/api/jobs/${encodeURIComponent(key)}`,{method:"PATCH",body:JSON.stringify(body)});toast("已保存");await load()}catch(e){toast(e.message)}}async function completeTask(id){try{await request(`/api/tasks/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status:"completed"})});toast("待办已完成");await load()}catch(e){toast(e.message)}}
function renderSearchOptions(){const d=state.search_defaults;if(!d)return;const escHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const roleLabelsMap={"AI Product":"AI Product","Product":"Product","UXR / Insight":"UXR / Insight","Management Trainee":"Management Trainee","Psychology Teaching":"心理教师相关（高校/职校/技校/中小学等）"};$("#role-family-options").innerHTML=(d.role_families||[]).map(v=>`<label class="check"><input type="checkbox" name="role_families" value="${escHtml(v)}" checked> ${escHtml(roleLabelsMap[v]||v)}</label>`).join("");$("#search-source-options").innerHTML=(d.sources||[]).map(v=>`<label class="check"><input type="checkbox" name="sources" value="${escHtml(v)}" checked> ${escHtml(v)}</label>`).join("")}async function load(){try{state=await request("/api/data");renderSearchOptions();fillOptions("#province",unique("province"),"全部地区");fillOptions("#role-family",unique("role_family"),"全部方向");$("#updated").textContent=`更新于 ${new Date(state.generated_at).toLocaleString("zh-CN")}`;renderStats();renderTabs();renderJobs();renderTasks()}catch(e){toast(`无法读取数据：${e.message}`)}}
function submitForm(form,url){form.addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.psychology_trigger=form.elements.psychology_trigger?.checked;try{await request(url,{method:"POST",body:JSON.stringify(data)});form.closest("dialog").close();form.reset();toast("已保存");await load()}catch(error){toast(error.message)}})}
$("#search").addEventListener("input",renderJobs);["#province","#role-family","#recruitment-type","#priority","#stage","#psychology"].forEach(s=>$(s).addEventListener("change",renderJobs));$("#refresh").onclick=load;$("#clear-filters").onclick=()=>{["#search","#province","#role-family","#recruitment-type","#priority","#stage"].forEach(s=>$(s).value="");$("#psychology").checked=false;selectedStage="";renderTabs();renderJobs()};$("#new-job").onclick=()=>$("#job-dialog").showModal();$("#new-task").onclick=()=>$("#task-dialog").showModal();$("#drawer-close").onclick=()=>$("#drawer").classList.remove("open");submitForm($("#job-form"),"/api/jobs");submitForm($("#task-form"),"/api/tasks");load();
